controller_num: 1
command_timeout: 0.5

motors: [
    {
    name: 'left_wheel_velocity_controller',
    motor_reversed: false,
    max_speed: 100,
    max_acceleration: 750,
    max_deceleration: 1000,
    max_duty_cycle: 100,
    max_current: 0.25,
    k_p: 15.0,
    k_i:  2.0,
    k_d:  0.5,
    encoder_pulses_per_revolution: 85 # 5 pulses * 17:1 gearing 
    },
    {
    name: 'right_wheel_velocity_controller',
    motor_reversed: true,
    max_speed: 100,
    max_acceleration: 750,
    max_deceleration: 1000,
    max_duty_cycle: 100,
    max_current: 0.25,
    k_p: 15.0,
    k_i:  2.0,
    k_d:  0.5,
    encoder_pulses_per_revolution: 85 # 5 pulses * 17:1 gearing 
    }
]

digital_inputs: []
