controller_num: 1
command_timeout: 0.5

motors: [
    {
    name: 'right_joint',
    motor_reversed: false,
    max_speed: 100,
    max_acceleration: 750,
    max_deceleration: 1000,
    max_duty_cycle: 100,
    max_current: 0.25,
    k_p: 2.0,
    k_i: 2.0,
    k_d: 0.0,
    encoder_pulses_per_revolution: 189 # 7 pulses * 27:1 gearing
    },
    {
    name: 'left_joint',
    motor_reversed: false,
    max_speed: 100,
    max_acceleration: 750,
    max_deceleration: 1000,
    max_duty_cycle: 100,
    max_current: 0.25,
    k_p: 2.0,
    k_i: 2.0,
    k_d: 0.0,
    encoder_pulses_per_revolution: 189 # 7 pulses * 27:1 gearing 
    }
]

digital_inputs: []
