#!/usr/bin/env python
import rospy
from geometry_msgs.msg import Pose2D




def start():
    rate = rospy.Rate(10)
    while not rospy.is_shutdown():
        if rospy.get_rostime() - start_time > rospy.Duration.from_sec(2.0) and rospy.get_rostime() - start_time < rospy.Duration.from_sec(17.6):
            msg.x = 0.0
            msg.y = -60.0
            msg.theta = 0.0
        elif rospy.get_rostime() - start_time > rospy.Duration.from_sec(20.0):
            break
        else:
            msg.x = 0.0
            msg.y = 0.0
            msg.theta = 0.0

        pub.publish(msg)
        rate.sleep()



if __name__ == '__main__':
    global pub
    rospy.init_node('Distance_test')
    pub = rospy.Publisher('robot_vel_goal', Pose2D, queue_size=100)

    global start_time
    global msg


    start_time = rospy.get_rostime()
    msg = Pose2D()


    start()
