#!/usr/bin/env python

# Before this will work:
# sudo rmmod xpad
# sudo su
# echo "blacklist xpad" > /etc/modprobe.d/blacklist.conf
# sudo add-apt-repository ppa:grumbel/ppa
# sudo apt-get update
# sudo apt-get install xboxdrv


# To start controlling
# sudo -S xboxdrv --silent

# Read the number of the controller
# rosparam set joy_node/dev "/dev/input/jsX"

# roslaunch omnicone xbox_control.launch
