#!/usr/bin/env python
import rospy
from sensor_msgs.msg import Joy
from geometry_msgs.msg import Pose2D

# Author: Andrew Dai
# This ROS Node converts Joystick inputs from the joy node
# into commands for turtlesim

# Receives joystick messages (subscribed to Joy topic)
# then converts the joysick inputs into Twist commands
# axis 1 aka left stick vertical controls linear speed
# axis 0 aka left stick horizonal controls angular speed
def callback(data):
    msg = Pose2D()
    msg.x = -1*data.axes[0]
    msg.y = 1*data.axes[1]
    msg.theta = 20*((data.axes[4]-1)-(data.axes[5]-1))
    pub.publish(msg)

# Intializes everything
def start():
    # publishing to "turtle1/cmd_vel" to control turtle1
    global pub
    rospy.init_node('Joy2Turtle')
    pub = rospy.Publisher('robot_vel_goal', Pose2D, queue_size=100)
    # subscribed to joystick inputs on topic "joy"
    rospy.Subscriber("joy", Joy, callback)
    # starts the node

    rospy.spin()

if __name__ == '__main__':
    start()
