# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'omni_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(667, 291)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.setDistanceBox = QtWidgets.QGroupBox(self.centralwidget)
        self.setDistanceBox.setGeometry(QtCore.QRect(180, 20, 131, 67))
        self.setDistanceBox.setObjectName("setDistanceBox")
        self.gridLayout = QtWidgets.QGridLayout(self.setDistanceBox)
        self.gridLayout.setObjectName("gridLayout")
        self.xSelect = QtWidgets.QRadioButton(self.setDistanceBox)
        self.xSelect.setChecked(True)
        self.xSelect.setObjectName("xSelect")
        self.gridLayout.addWidget(self.xSelect, 1, 1, 1, 1)
        self.ySelect = QtWidgets.QRadioButton(self.setDistanceBox)
        self.ySelect.setObjectName("ySelect")
        self.gridLayout.addWidget(self.ySelect, 1, 2, 1, 1)
        self.displayBox = QtWidgets.QGroupBox(self.centralwidget)
        self.displayBox.setGeometry(QtCore.QRect(510, 10, 141, 130))
        self.displayBox.setObjectName("displayBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.displayBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.xDisplayLabel = QtWidgets.QLabel(self.displayBox)
        self.xDisplayLabel.setObjectName("xDisplayLabel")
        self.verticalLayout.addWidget(self.xDisplayLabel, 0, QtCore.Qt.AlignHCenter)
        self.xDisplay = QtWidgets.QLabel(self.displayBox)
        self.xDisplay.setObjectName("xDisplay")
        self.verticalLayout.addWidget(self.xDisplay, 0, QtCore.Qt.AlignHCenter)
        self.yDisplayLabel = QtWidgets.QLabel(self.displayBox)
        self.yDisplayLabel.setObjectName("yDisplayLabel")
        self.verticalLayout.addWidget(self.yDisplayLabel, 0, QtCore.Qt.AlignHCenter)
        self.yDisplay = QtWidgets.QLabel(self.displayBox)
        self.yDisplay.setObjectName("yDisplay")
        self.verticalLayout.addWidget(self.yDisplay, 0, QtCore.Qt.AlignHCenter)
        self.goButton = QtWidgets.QPushButton(self.centralwidget)
        self.goButton.setGeometry(QtCore.QRect(540, 220, 80, 25))
        self.goButton.setObjectName("goButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 90, 404, 168))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button9 = QtWidgets.QPushButton(self.groupBox)
        self.button9.setObjectName("button9")
        self.gridLayout_2.addWidget(self.button9, 5, 4, 1, 1)
        self.button7 = QtWidgets.QPushButton(self.groupBox)
        self.button7.setObjectName("button7")
        self.gridLayout_2.addWidget(self.button7, 5, 2, 1, 1)
        self.button3 = QtWidgets.QPushButton(self.groupBox)
        self.button3.setObjectName("button3")
        self.gridLayout_2.addWidget(self.button3, 1, 4, 1, 1)
        self.button5 = QtWidgets.QPushButton(self.groupBox)
        self.button5.setObjectName("button5")
        self.gridLayout_2.addWidget(self.button5, 3, 3, 1, 1)
        self.button2 = QtWidgets.QPushButton(self.groupBox)
        self.button2.setObjectName("button2")
        self.gridLayout_2.addWidget(self.button2, 1, 3, 1, 1)
        self.button1 = QtWidgets.QPushButton(self.groupBox)
        self.button1.setObjectName("button1")
        self.gridLayout_2.addWidget(self.button1, 1, 2, 1, 1)
        self.button0 = QtWidgets.QPushButton(self.groupBox)
        self.button0.setObjectName("button0")
        self.gridLayout_2.addWidget(self.button0, 6, 3, 1, 1)
        self.button4 = QtWidgets.QPushButton(self.groupBox)
        self.button4.setObjectName("button4")
        self.gridLayout_2.addWidget(self.button4, 3, 2, 1, 1)
        self.button8 = QtWidgets.QPushButton(self.groupBox)
        self.button8.setObjectName("button8")
        self.gridLayout_2.addWidget(self.button8, 5, 3, 1, 1)
        self.button6 = QtWidgets.QPushButton(self.groupBox)
        self.button6.setObjectName("button6")
        self.gridLayout_2.addWidget(self.button6, 3, 4, 1, 1)
        self.signButton = QtWidgets.QPushButton(self.groupBox)
        self.signButton.setObjectName("signButton")
        self.gridLayout_2.addWidget(self.signButton, 6, 2, 1, 1)
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(540, 150, 89, 25))
        self.resetButton.setObjectName("resetButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.setDistanceBox.setTitle(_translate("MainWindow", "Select Direction"))
        self.xSelect.setText(_translate("MainWindow", "x"))
        self.ySelect.setText(_translate("MainWindow", "y"))
        self.displayBox.setTitle(_translate("MainWindow", "Current Distance set"))
        self.xDisplayLabel.setText(_translate("MainWindow", "x"))
        self.xDisplay.setText(_translate("MainWindow", "0.0"))
        self.yDisplayLabel.setText(_translate("MainWindow", "y"))
        self.yDisplay.setText(_translate("MainWindow", "0.0"))
        self.goButton.setText(_translate("MainWindow", "Go"))
        self.groupBox.setTitle(_translate("MainWindow", "Insert Distance (m)"))
        self.button9.setText(_translate("MainWindow", "9"))
        self.button7.setText(_translate("MainWindow", "7"))
        self.button3.setText(_translate("MainWindow", "3"))
        self.button5.setText(_translate("MainWindow", "5"))
        self.button2.setText(_translate("MainWindow", "2"))
        self.button1.setText(_translate("MainWindow", "1"))
        self.button0.setText(_translate("MainWindow", "0"))
        self.button4.setText(_translate("MainWindow", "4"))
        self.button8.setText(_translate("MainWindow", "8"))
        self.button6.setText(_translate("MainWindow", "6"))
        self.signButton.setText(_translate("MainWindow", "-/+"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))

