#!/usr/bin/env python3

from sys import argv

print("const char* " +  argv[1] + "[] = {")
with open(argv[2]) as f:
    for line in f.readlines():
        print('  "' + line.strip() + '",' )
print("  0")
print("};")
