#!/usr/bin/env python
import csv
import math as m


with open('waypoints','rb') as f:
    reader = csv.reader(f,delimiter=',')
    spot = 0;
    spd = {}
    ang = {}
    lat = {}
    lng = {}
    for row in reader:
        lat[spot] = float(row[0])
        lng[spot] = float(row[1])
        spd[spot] = float(row[2])
        ang[spot] = float(row[3])
        spot += 1
    f.close
    speeds = [0.5, 1, 2, 3, 4, 5, 7, 10, 12, 15, 20]
    for dspd in speeds:
        with open('waypoints_' + str(dspd), 'wb') as f:
            writer = csv.writer(f, delimiter=',')
            for j in range(0,spot):
                if(j == 0):
                    newspd = float(dspd)
                elif(spd[j] < 0):
                    newspd = spd[j]
                else:
                    min = 100
                    a = int(dspd)
                    l1 = -2*a if 2*a < j else -j
                    l2 = 5*a if 5*a < spot-j else spot-j
                    for k in range(l1,l2):
                        if ang[j+k] == 0:
                            continue
                        sp = m.sqrt(abs(spd[j+k]/ang[j+k])/2) 
                        if sp < min:
                            min = sp
                    newspd = min if min < float(dspd) else float(dspd)
                writer.writerow([lat[j],lng[j],newspd])
        f.close
